### ISSUE TITLE
Crash with xnet-1.16-3.0.11

### ISSUE THREAD

**Issue by rainsillwood** [HalogenMods/Chlorine#9]
Crash when placing xnet cables

[14:25:47] [Chunk Render Task Executor #4/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NullPointerException
[14:25:47] [Chunk Render Task Executor #4/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at mcjty.xnet.modules.cables.client.GenericCableBakedModel.getQuads(GenericCableBakedModel.java:312)
[14:25:47] [Chunk Render Task Executor #4/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderModel(BlockRenderer.java:69)
[14:25:47] [Chunk Render Task Executor #4/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at me.jellysquid.mods.sodium.client.render.pipeline.context.ChunkRenderContext.renderBlock(ChunkRenderContext.java:44)
[14:25:47] [Chunk Render Task Executor #4/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:102)
[14:25:47] [Chunk Render Task Executor #4/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:344)
[14:25:47] [Chunk Render Task Executor #4/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Thread.run(Unknown Source)

**Comment by Sparktion** [comment]
Still happening.
